[projects]

  [projects.default]

  homepage_contents = "index"
  metadata_path = "metadata.yml"

  contents = [
    "index"
  ]

  # Extra directories to be copied.
  extra_directories = [
    "images",
  ]

  # Port used by serve()
  port = 8010

  # Output filename for the PDF.
  output_filename = "analysis"

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://github.com/ivaquero/ivaquero.github.io"
